apiVersion: v1
kind: Secret
metadata:
  name: frr-k8s-webhook-server-cert
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: frr-k8s-webhook-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - port: 443
    targetPort: webhook
  selector:
    component: statuscleaner
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: frr-k8s-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: frr-k8s-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-frrk8s-metallb-io-v1beta1-frrconfiguration
  failurePolicy: {{ .Values.crds.validationFailurePolicy }}
  name: frrconfigurationsvalidationwebhook.metallb.io
  rules:
  - apiGroups:
    - frrk8s.metallb.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - frrconfigurations
  sideEffects: None
