apiVersion: v1
kind: Namespace
metadata:
  name: mymetallb
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: metallb-operator
  namespace: mymetallb
spec:
  displayName: MetalLB Operator Upstream
  image: quay.io/metallb/metallb-operator-bundle-index:v0.13.11
  publisher: github.com/metallb/metallb-operator
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: metallb-operator
  namespace: mymetallb
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator-sub
  namespace: mymetallb
spec:
  name: metallb-operator
  channel: alpha
  source: metallb-operator
  sourceNamespace: mymetallb
